package co.unicauca.formata.model;
public enum EstadoProyecto {
    FORMATO_A_EN_EVALUACION,
    FORMATO_A_RECHAZADO,
    FORMATO_A_ACEPTADO,
    ANTEPROYECTO_SUBIDO,
    ANTEPROYECTO_EN_EVALUACION,
    ANTEPROYECTO_RECHAZADO,
    ANTEPROYECTO_ACEPTADO
}